export const MESSAGE = {
  SUCCESS: 'Success',
  FAILED: 'Failed',
  ERROR_MSG: 'Something went wrong. Please try again.',
  USER_NOT_FOUND_ERROR: 'User not found',
  USER_UPDATED_SUCCESS: 'User profile updated successfully',
  FIRST_NAME_ERROR: 'First name is required',
  FIRST_NAME_MIN_ERROR: 'First name length should be at least 2 characters',
  LAST_NAME_ERROR: 'Last name is required',
  LAST_NAME_MIN_ERROR: 'Last name length should be at least 2 characters',
  EMAIL_ERROR: 'Email address is required',
  EMAIL_NOT_VALID: 'Email address is not valid',
  PASSWORD_ERROR: 'Password is required',
  PASSWORD_NOT_VALID:
    'Password must contain at least 8 characters, including a upper/lowercase, symbols and numbers.',
  USER_NAME_ERROR: 'User name is required',
  USERNAME_LENGTH_NOT_VALID: 'Username length should be between 6 and 30.',
  USER_ADDED_SUCCESS: 'User profile created successfully',
  USER_ID_NOT_VALID: 'User id is not valid',
  USER_ALREADY_EXIST: 'User already exists',
  LOGIN_SUCCESS: 'Log in successfully',
  LOGIN_ERROR: 'Invalid email or password',
  ACCESS_DENIED: 'You are not authorized to access this resource.',
  ALREADY_REGISTER:
    'There was a problem creating your account. Check that your email address or username is spelled correctly and try again',
  EMAIL_SENT: 'A mail send to your email address to verify the OTP',
};
